<?php
use App\Services\FinanceService;
$finance=new FinanceService($db);$balance=$finance->cashBalance();
$from=$_GET['from']??date('Y-m-01');$to=$_GET['to']??date('Y-m-t');
$ledger=$db->fetchAll("SELECT * FROM (
 SELECT CONCAT('payment-',p.id) row_id,'payment' source,p.id,(CASE WHEN p.currency='USD' THEN COALESCE(p.settlement_date,p.payment_date) ELSE p.payment_date END) entry_date,'in' direction,COALESCE(p.description,CONCAT('Pagamento · ',c.name)) description,p.net_brl amount_brl,p.currency,p.amount original_amount,p.status
 FROM payments p JOIN clients c ON c.id=p.client_id WHERE p.status='paid' AND (CASE WHEN p.currency='USD' THEN COALESCE(p.settlement_date,p.payment_date) ELSE p.payment_date END) BETWEEN ? AND ?
 UNION ALL
 SELECT CONCAT('expense-',e.id),'expense',e.id,e.payment_date,'out',e.description,e.amount_brl,e.currency,e.amount,e.status FROM expenses e WHERE e.status='paid' AND e.payment_date BETWEEN ? AND ?
 UNION ALL
 SELECT CONCAT('cash-',x.id),'cash',x.id,x.entry_date,x.direction,x.description,x.amount_brl,x.currency,x.amount,'paid' FROM cash_entries x WHERE x.entry_date BETWEEN ? AND ?
) ledger ORDER BY entry_date DESC,row_id DESC LIMIT 300",[$from,$to,$from,$to,$from,$to]);
$periodIn=0;$periodOut=0;foreach($ledger as $row){if($row['direction']==='in')$periodIn+=(float)$row['amount_brl'];else$periodOut+=(float)$row['amount_brl'];}
$edit=isset($_GET['edit'])?$db->fetch('SELECT * FROM cash_entries WHERE id=?',[(int)$_GET['edit']]):null;$showForm=isset($_GET['new'])||$edit;
?>
<section class="cash-hero"><article><span>SALDO DE CAIXA CONSOLIDADO</span><strong class="<?= $balance<0?'negative':'' ?>"><?= money($balance) ?></strong><small>Pagamentos líquidos + entradas − gastos − saídas</small></article><article><span>ENTRADAS NO PERÍODO</span><strong class="positive">＋ <?= money($periodIn) ?></strong><small><?= date_br($from) ?> a <?= date_br($to) ?></small></article><article><span>SAÍDAS NO PERÍODO</span><strong class="negative">− <?= money($periodOut) ?></strong><small><?= date_br($from) ?> a <?= date_br($to) ?></small></article></section>
<section class="toolbar list-toolbar"><form class="search-filters" method="get"><input type="hidden" name="page" value="cash"><label>De<input type="date" name="from" value="<?= h($from) ?>"></label><label>Até<input type="date" name="to" value="<?= h($to) ?>"></label><button class="button secondary">Aplicar</button></form><?php if($auth->canWrite()): ?><a class="button primary" href="?page=cash&new=1">＋ Movimento avulso</a><?php endif; ?></section>
<section class="card table-card"><div class="card-header padded"><div><p class="eyebrow">EXTRATO UNIFICADO</p><h2>Movimentações do período</h2></div><span class="muted">Até 300 lançamentos</span></div><div class="table-wrap"><table><thead><tr><th>Movimentação</th><th>Origem</th><th>Data</th><th>Valor original</th><th>Entrada / saída</th><th></th></tr></thead><tbody>
<?php if(!$ledger): ?><tr><td colspan="6" class="empty-cell">Nenhuma movimentação no período.</td></tr><?php endif; ?>
<?php foreach($ledger as $item): ?><tr><td><div class="entity"><span class="flow-icon <?= $item['direction']==='in'?'in':'out' ?>"><?= $item['direction']==='in'?'↓':'↑' ?></span><b><?= h($item['description']) ?></b></div></td><td><span class="badge muted"><?= ['payment'=>'Pagamento','expense'=>'Gasto / investimento','cash'=>'Avulso'][$item['source']] ?></span></td><td><?= date_br($item['entry_date']) ?></td><td><?= money($item['original_amount'],$item['currency']) ?></td><td><b class="<?= $item['direction']==='in'?'positive':'negative' ?>"><?= $item['direction']==='in'?'+ ':'− ' ?><?= money($item['amount_brl']) ?></b></td><td><?= $item['source']==='cash'?'<a class="row-action" href="?page=cash&edit='.(int)$item['id'].'">•••</a>':'<span class="lock-icon" title="Edite no módulo de origem">⌁</span>' ?></td></tr><?php endforeach; ?>
</tbody></table></div></section>
<?php if($showForm): ?><div class="modal open"><a class="modal-backdrop" href="?page=cash"></a><section class="modal-panel"><header><div><p class="eyebrow">CAIXA AVULSO</p><h2><?= $edit?'Editar movimento':'Novo movimento' ?></h2></div><a href="?page=cash" class="modal-close">×</a></header><div class="form-note">Use este formulário para aportes, retiradas, ajustes e outras movimentações que não sejam pagamentos de clientes nem gastos.</div><form method="post" class="form-grid" data-money-form data-daily-rate="1" data-new-record="<?= $edit?'0':'1' ?>"><?= csrf_field() ?><input type="hidden" name="action" value="save_cash"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><input type="hidden" name="_return" value="<?= h($_SERVER['REQUEST_URI']) ?>">
<label>Direção<select name="direction"><option value="in" <?= ($edit['direction']??'in')==='in'?'selected':'' ?>>Entrada</option><option value="out" <?= ($edit['direction']??'')==='out'?'selected':'' ?>>Saída</option></select></label><label>Categoria<input name="category" required value="<?= h($edit['category']??'') ?>" placeholder="Aporte, retirada, ajuste…"></label><label class="span-2">Descrição<input name="description" required value="<?= h($edit['description']??'') ?>"></label><label>Moeda<select name="currency" data-money-currency><option value="BRL" <?= ($edit['currency']??'BRL')==='BRL'?'selected':'' ?>>BRL — Real</option><option value="USD" <?= ($edit['currency']??'')==='USD'?'selected':'' ?>>USD — Dólar</option></select></label><label>Valor<input name="amount" type="number" step="0.01" min="0.01" required data-money-amount value="<?= decimal_input($edit['amount']??0) ?>"></label><input type="hidden" data-money-fee value="0"><label>Cotação USD → BRL<input name="exchange_rate" type="number" step="0.000001" min="0" data-money-rate value="<?= h($edit['exchange_rate']??'') ?>" placeholder="Automática pela data"><small data-rate-help><?= $edit?'Cotação histórica deste movimento':'Aguardando a moeda e a data' ?></small></label><label>Data<input name="entry_date" type="date" required data-rate-date value="<?= h($edit['entry_date']??date('Y-m-d')) ?>"></label><div class="conversion-preview span-2"><span>Total convertido</span><strong data-money-preview>R$ 0,00</strong></div><label class="span-2">Observações<textarea name="notes" rows="3"><?= h($edit['notes']??'') ?></textarea></label><footer class="span-2"><a class="button ghost" href="?page=cash">Cancelar</a><button class="button primary">Salvar movimento</button></footer></form><?php if($edit&&$auth->canWrite()): ?><form method="post" class="danger-zone" data-confirm="Excluir esta movimentação?"><?= csrf_field() ?><input type="hidden" name="action" value="delete_cash"><input type="hidden" name="id" value="<?= (int)$edit['id'] ?>"><button>Excluir movimento</button></form><?php endif; ?></section></div><?php endif; ?>
