<?php
$search = trim((string) ($_GET['q'] ?? ''));
$status = (string) ($_GET['status'] ?? '');
$where = ' WHERE 1=1'; $params = [];
if ($search !== '') { $where .= " AND CONCAT_WS(' ',c.id,c.name,c.company,c.email,c.phone,c.document,c.country,CASE c.country WHEN 'BR' THEN 'Brasil' WHEN 'US' THEN 'Estados Unidos' END,c.preferred_currency,c.status,CASE c.status WHEN 'active' THEN 'Ativo' WHEN 'lead' THEN 'Lead' WHEN 'inactive' THEN 'Inativo' END,c.notes,(SELECT COUNT(*) FROM subscriptions sx WHERE sx.client_id=c.id AND sx.status='active'),'assinaturas') LIKE ?"; $params[]='%'.$search.'%'; }
if (in_array($status,['lead','active','inactive'],true)) { $where .= ' AND c.status=?'; $params[]=$status; }
$pagination = pagination($db, 'SELECT COUNT(*) FROM clients c'.$where, "SELECT c.*, (SELECT COUNT(*) FROM subscriptions s WHERE s.client_id=c.id AND s.status='active') active_subscriptions FROM clients c".$where.' ORDER BY c.created_at DESC', $params);
$edit = isset($_GET['edit']) ? $db->fetch('SELECT * FROM clients WHERE id=?',[(int)$_GET['edit']]) : null;
$showForm = isset($_GET['new']) || $edit;
?>
<section class="toolbar list-toolbar"><form class="search-filters" method="get" data-live-filter><input type="hidden" name="page" value="clients"><label class="search-box">⌕<input name="q" autocomplete="off" placeholder="Buscar qualquer informação" value="<?= h($search) ?>"></label><select name="status"><option value="">Todos os status</option><option value="active" <?= $status==='active'?'selected':'' ?>>Ativos</option><option value="lead" <?= $status==='lead'?'selected':'' ?>>Leads</option><option value="inactive" <?= $status==='inactive'?'selected':'' ?>>Inativos</option></select><span class="live-filter-indicator" data-live-filter-indicator aria-live="polite">Busca automática</span></form><div><a class="button ghost" href="?page=export&type=clients">⇩ Exportar</a><?php if($auth->canWrite()): ?><a class="button primary" href="?page=clients&new=1">＋ Novo cliente</a><?php endif; ?></div></section>
<div data-live-results>
<section class="card table-card">
    <div class="table-meta"><span><b><?= $pagination['total'] ?></b> clientes encontrados</span></div>
    <div class="table-wrap"><table><thead><tr><th>Cliente</th><th>País</th><th>Moeda</th><th>Assinaturas</th><th>Status</th><th></th></tr></thead><tbody>
    <?php if(!$pagination['rows']): ?><tr><td colspan="6" class="empty-cell">Nenhum cliente encontrado. Cadastre o primeiro cliente para começar.</td></tr><?php endif; ?>
    <?php foreach($pagination['rows'] as $item): ?><tr><td><div class="entity"><span class="avatar-sm"><?= h(mb_strtoupper(mb_substr($item['name'],0,1))) ?></span><span><b><?= h($item['name']) ?></b><small><?= h($item['company'] ?: $item['email'] ?: 'Sem contato informado') ?></small></span></div></td><td><span class="country-cell"><?= country_flag_icon($item['country']) ?><span><?= $item['country']==='BR'?'Brasil':'Estados Unidos' ?></span></span></td><td><b><?= h($item['preferred_currency']) ?></b></td><td><?= (int)$item['active_subscriptions'] ?> ativa(s)</td><td><span class="badge <?= status_class($item['status']) ?>"><?= status_label($item['status']) ?></span></td><td><a class="row-action" href="?page=clients&edit=<?= (int)$item['id'] ?>" aria-label="Editar">•••</a></td></tr><?php endforeach; ?>
    </tbody></table></div><?= render_pagination($pagination) ?>
</section>
</div>
<?php if($showForm): ?>
<div class="modal open"><a class="modal-backdrop" href="?page=clients"></a><section class="modal-panel"><header><div><p class="eyebrow">CLIENTES</p><h2><?= $edit?'Editar cliente':'Novo cliente' ?></h2></div><a href="?page=clients" class="modal-close">×</a></header><form method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="save_client"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><input type="hidden" name="_return" value="<?= h($_SERVER['REQUEST_URI']) ?>">
<label class="span-2">Nome completo ou razão social<input name="name" required value="<?= h($edit['name']??'') ?>"></label><label>Empresa<input name="company" value="<?= h($edit['company']??'') ?>"></label><label>E-mail<input name="email" type="email" value="<?= h($edit['email']??'') ?>"></label><label>WhatsApp<input name="phone" inputmode="tel" value="<?= h($edit['phone']??'') ?>" placeholder="Ex.: 55 11 99999-9999"><small>Informe DDI, DDD e número para receber lembretes.</small></label><label>CPF, CNPJ ou Tax ID<input name="document" value="<?= h($edit['document']??'') ?>"></label><label>País<select name="country" data-country><option value="BR" <?= ($edit['country']??'BR')==='BR'?'selected':'' ?>>Brasil</option><option value="US" <?= ($edit['country']??'')==='US'?'selected':'' ?>>Estados Unidos</option></select></label><label>Moeda preferida<select name="preferred_currency" data-currency><option value="BRL" <?= ($edit['preferred_currency']??'BRL')==='BRL'?'selected':'' ?>>BRL — Real</option><option value="USD" <?= ($edit['preferred_currency']??'')==='USD'?'selected':'' ?>>USD — Dólar</option></select></label><label class="span-2">Status<select name="status"><option value="active" <?= ($edit['status']??'active')==='active'?'selected':'' ?>>Ativo</option><option value="lead" <?= ($edit['status']??'')==='lead'?'selected':'' ?>>Lead</option><option value="inactive" <?= ($edit['status']??'')==='inactive'?'selected':'' ?>>Inativo</option></select></label><label class="span-2">Observações<textarea name="notes" rows="3"><?= h($edit['notes']??'') ?></textarea></label><footer class="span-2"><a class="button ghost" href="?page=clients">Cancelar</a><button class="button primary">Salvar cliente</button></footer></form>
<?php if($edit&&$auth->canWrite()): ?><form method="post" class="danger-zone" data-confirm="Excluir este cliente? Esta ação não pode ser desfeita."><?= csrf_field() ?><input type="hidden" name="action" value="delete_client"><input type="hidden" name="id" value="<?= (int)$edit['id'] ?>"><button>Excluir cliente</button></form><?php endif; ?></section></div>
<?php endif; ?>
