<?php
$search=trim((string)($_GET['q']??'')); $type=(string)($_GET['type']??''); $status=(string)($_GET['status']??''); $where=' WHERE 1=1';$params=[];
if($search!==''){ $where.=' AND (description LIKE ? OR category LIKE ? OR supplier LIKE ?)';$like='%'.$search.'%';$params=[$like,$like,$like]; }
if(in_array($type,['expense','investment'],true)){ $where.=' AND type=?';$params[]=$type; }
if(in_array($status,['paid','pending'],true)){ $where.=' AND status=?';$params[]=$status; }
$pagination=pagination($db,'SELECT COUNT(*) FROM expenses'.$where,'SELECT * FROM expenses'.$where.' ORDER BY payment_date DESC,id DESC',$params);
$edit=isset($_GET['edit'])?$db->fetch('SELECT * FROM expenses WHERE id=?',[(int)$_GET['edit']]):null;$showForm=isset($_GET['new'])||$edit;$currentRate=$showForm?$rates->current():null;
$month=$db->fetch("SELECT COALESCE(SUM(CASE WHEN type='expense' AND status='paid' THEN amount_brl ELSE 0 END),0) expenses,COALESCE(SUM(CASE WHEN type='investment' AND status='paid' THEN amount_brl ELSE 0 END),0) investments,COALESCE(SUM(CASE WHEN status='pending' THEN amount_brl ELSE 0 END),0) pending FROM expenses WHERE payment_date BETWEEN ? AND ?",[date('Y-m-01'),date('Y-m-t')]);
$categories=['Marketing','Software e ferramentas','Impostos','Equipe e prestadores','Infraestrutura','Administrativo','Jurídico e contábil','Viagens','Outros'];
?>
<section class="mini-stats money-stats"><div><span class="dot red"></span><span><small>Despesas no mês</small><b><?= money($month['expenses']) ?></b></span></div><div><span class="dot purple"></span><span><small>Investimentos no mês</small><b><?= money($month['investments']) ?></b></span></div><div><span class="dot gold"></span><span><small>A pagar</small><b><?= money($month['pending']) ?></b></span></div></section>
<section class="toolbar list-toolbar"><form class="search-filters" method="get"><input type="hidden" name="page" value="expenses"><label class="search-box">⌕<input name="q" placeholder="Descrição, categoria ou fornecedor" value="<?= h($search) ?>"></label><select name="type"><option value="">Despesas + investimentos</option><option value="expense" <?= $type==='expense'?'selected':'' ?>>Despesas</option><option value="investment" <?= $type==='investment'?'selected':'' ?>>Investimentos</option></select><select name="status"><option value="">Todos</option><option value="paid" <?= $status==='paid'?'selected':'' ?>>Pagos</option><option value="pending" <?= $status==='pending'?'selected':'' ?>>Pendentes</option></select><button class="button secondary">Filtrar</button></form><div><a class="button ghost" href="?page=export&type=expenses">⇩ Exportar</a><?php if($auth->canWrite()): ?><a class="button primary" href="?page=expenses&new=1">＋ Novo lançamento</a><?php endif; ?></div></section>
<section class="card table-card"><div class="table-meta"><span><b><?= $pagination['total'] ?></b> lançamentos</span></div><div class="table-wrap"><table><thead><tr><th>Descrição</th><th>Tipo / Categoria</th><th>Data</th><th>Valor original</th><th>Total em BRL</th><th>Status</th><th></th></tr></thead><tbody>
<?php if(!$pagination['rows']): ?><tr><td colspan="7" class="empty-cell">Nenhum gasto ou investimento encontrado.</td></tr><?php endif; ?>
<?php foreach($pagination['rows'] as $item): ?><tr><td><div class="entity"><span class="expense-icon <?= $item['type']==='investment'?'purple':'red' ?>"><?= $item['type']==='investment'?'↗':'↑' ?></span><span><b><?= h($item['description']) ?></b><small><?= h($item['supplier']?:'Sem fornecedor') ?><?= $item['is_recurring']?' · Recorrente':'' ?></small></span></div></td><td><span class="badge <?= $item['type']==='investment'?'info':'muted' ?>"><?= $item['type']==='investment'?'Investimento':'Despesa' ?></span><small class="block"><?= h($item['category']) ?></small></td><td><?= date_br($item['payment_date']) ?></td><td><b><?= money($item['amount'],$item['currency']) ?></b><?php if($item['currency']==='USD'): ?><small class="block">USD × <?= number_format($item['exchange_rate'],4,',','.') ?></small><?php endif; ?></td><td><b><?= money($item['amount_brl']) ?></b></td><td><span class="badge <?= status_class($item['status']) ?>"><?= status_label($item['status']) ?></span></td><td><a class="row-action" href="?page=expenses&edit=<?= (int)$item['id'] ?>">•••</a></td></tr><?php endforeach; ?>
</tbody></table></div><?= render_pagination($pagination) ?></section>
<?php if($showForm): ?><div class="modal open"><a class="modal-backdrop" href="?page=expenses"></a><section class="modal-panel wide"><header><div><p class="eyebrow">SAÍDAS</p><h2><?= $edit?'Editar lançamento':'Novo gasto ou investimento' ?></h2></div><a href="?page=expenses" class="modal-close">×</a></header><form method="post" class="form-grid" data-money-form data-current-rate="<?= h($currentRate['bid']) ?>"><?= csrf_field() ?><input type="hidden" name="action" value="save_expense"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><input type="hidden" name="_return" value="<?= h($_SERVER['REQUEST_URI']) ?>">
<label>Tipo<select name="type"><option value="expense" <?= ($edit['type']??'expense')==='expense'?'selected':'' ?>>Despesa operacional</option><option value="investment" <?= ($edit['type']??'')==='investment'?'selected':'' ?>>Investimento em crescimento</option></select></label><label>Categoria<select name="category" required><option value="">Selecione…</option><?php foreach($categories as $category): ?><option <?= ($edit['category']??'')===$category?'selected':'' ?>><?= h($category) ?></option><?php endforeach; ?></select></label><label class="span-2">Descrição<input name="description" required value="<?= h($edit['description']??'') ?>" placeholder="O que foi pago?"></label><label class="span-2">Fornecedor ou favorecido<input name="supplier" value="<?= h($edit['supplier']??'') ?>"></label><label>Moeda<select name="currency" data-money-currency><option value="BRL" <?= ($edit['currency']??'BRL')==='BRL'?'selected':'' ?>>BRL — Real</option><option value="USD" <?= ($edit['currency']??'')==='USD'?'selected':'' ?>>USD — Dólar</option></select></label><label>Valor<input name="amount" type="number" min="0.01" step="0.01" required data-money-amount value="<?= decimal_input($edit['amount']??0) ?>"></label><input type="hidden" data-money-fee value="0"><label>Cotação USD → BRL<input name="exchange_rate" type="number" step="0.000001" min="0" data-money-rate value="<?= h($edit['exchange_rate']??$currentRate['bid']) ?>"><small><?= $edit?'Cotação histórica deste lançamento':'Cotação comercial atual' ?></small></label><label>Data<input name="payment_date" type="date" required value="<?= h($edit['payment_date']??date('Y-m-d')) ?>"></label><div class="conversion-preview span-2"><span>Total convertido</span><strong data-money-preview>R$ 0,00</strong><small>A conversão é salva para manter o histórico correto.</small></div><label>Status<select name="status"><option value="paid" <?= ($edit['status']??'paid')==='paid'?'selected':'' ?>>Pago</option><option value="pending" <?= ($edit['status']??'')==='pending'?'selected':'' ?>>Pendente</option></select></label><label class="check-label check-inline"><input type="checkbox" name="is_recurring" value="1" <?= ($edit['is_recurring']??0)?'checked':'' ?>><span>Este gasto é recorrente</span></label><label class="span-2">Observações<textarea name="notes" rows="3"><?= h($edit['notes']??'') ?></textarea></label><footer class="span-2"><a class="button ghost" href="?page=expenses">Cancelar</a><button class="button primary">Salvar lançamento</button></footer></form><?php if($edit&&$auth->canWrite()): ?><form method="post" class="danger-zone" data-confirm="Excluir este lançamento?"><?= csrf_field() ?><input type="hidden" name="action" value="delete_expense"><input type="hidden" name="id" value="<?= (int)$edit['id'] ?>"><button>Excluir lançamento</button></form><?php endif; ?></section></div><?php endif; ?>

