<?php
$search=trim((string)($_GET['q']??'')); $params=[]; $where='';
if($search!==''){ $where=' WHERE name LIKE ? OR sku LIKE ?'; $params=['%'.$search.'%','%'.$search.'%']; }
$pagination=pagination($db,'SELECT COUNT(*) FROM products'.$where,'SELECT p.*, (SELECT COUNT(*) FROM subscriptions s WHERE s.product_id=p.id AND s.status=\'active\') active_subscriptions FROM products p'.$where.' ORDER BY p.active DESC,p.created_at DESC',$params);
$edit=isset($_GET['edit'])?$db->fetch('SELECT * FROM products WHERE id=?',[(int)$_GET['edit']]):null; $showForm=isset($_GET['new'])||$edit;
?>
<section class="toolbar list-toolbar"><form class="search-filters" method="get"><input type="hidden" name="page" value="products"><label class="search-box">⌕<input name="q" placeholder="Buscar produto ou SKU" value="<?= h($search) ?>"></label><button class="button secondary">Buscar</button></form><?php if($auth->canWrite()): ?><a class="button primary" href="?page=products&new=1">＋ Novo produto</a><?php endif; ?></section>
<section class="product-grid">
<?php if(!$pagination['rows']): ?><article class="card empty-state span-full"><span>◇</span><h2>Nenhum produto cadastrado</h2><p>Cadastre seus planos com preços locais em real e dólar.</p><a class="button primary" href="?page=products&new=1">Criar primeiro produto</a></article><?php endif; ?>
<?php foreach($pagination['rows'] as $item): ?><article class="card product-card <?= !$item['active']?'disabled':'' ?>"><div class="product-top"><span class="product-icon">◇</span><span class="badge <?= $item['active']?'success':'muted' ?>"><?= $item['active']?'Ativo':'Inativo' ?></span></div><h2><?= h($item['name']) ?></h2><p><?= h($item['description'] ?: 'Sem descrição') ?></p><div class="local-prices"><div><small>🇧🇷 BRASIL</small><strong><?= money($item['price_brl']) ?></strong></div><div><small>🇺🇸 ESTADOS UNIDOS</small><strong><?= money($item['price_usd'],'USD') ?></strong></div></div><footer><span><?= cycle_label($item['billing_cycle']) ?> · <?= (int)$item['active_subscriptions'] ?> assinaturas</span><a href="?page=products&edit=<?= (int)$item['id'] ?>">Editar →</a></footer></article><?php endforeach; ?>
</section><?= render_pagination($pagination) ?>
<?php if($showForm): ?><div class="modal open"><a class="modal-backdrop" href="?page=products"></a><section class="modal-panel"><header><div><p class="eyebrow">CATÁLOGO</p><h2><?= $edit?'Editar produto':'Novo produto' ?></h2></div><a href="?page=products" class="modal-close">×</a></header><form method="post" class="form-grid"><?= csrf_field() ?><input type="hidden" name="action" value="save_product"><input type="hidden" name="id" value="<?= (int)($edit['id']??0) ?>"><input type="hidden" name="_return" value="<?= h($_SERVER['REQUEST_URI']) ?>"><label class="span-2">Nome do produto<input name="name" required value="<?= h($edit['name']??'') ?>"></label><label>SKU<input name="sku" value="<?= h($edit['sku']??'') ?>" placeholder="PLANO-PRO"></label><label>Ciclo de cobrança<select name="billing_cycle"><option value="monthly" <?= ($edit['billing_cycle']??'monthly')==='monthly'?'selected':'' ?>>Mensal</option><option value="quarterly" <?= ($edit['billing_cycle']??'')==='quarterly'?'selected':'' ?>>Trimestral</option><option value="semiannual" <?= ($edit['billing_cycle']??'')==='semiannual'?'selected':'' ?>>Semestral</option><option value="annual" <?= ($edit['billing_cycle']??'')==='annual'?'selected':'' ?>>Anual</option></select></label><label>Preço no Brasil (R$)<input name="price_brl" type="number" min="0" step="0.01" required value="<?= decimal_input($edit['price_brl']??0) ?>"></label><label>Preço nos EUA (US$)<input name="price_usd" type="number" min="0" step="0.01" required value="<?= decimal_input($edit['price_usd']??0) ?>"></label><label class="span-2">Descrição<textarea name="description" rows="3"><?= h($edit['description']??'') ?></textarea></label><label class="check-label span-2"><input type="checkbox" name="active" value="1" <?= !isset($edit['active'])||$edit['active']?'checked':'' ?>><span>Produto disponível para novas assinaturas</span></label><footer class="span-2"><a class="button ghost" href="?page=products">Cancelar</a><button class="button primary">Salvar produto</button></footer></form><?php if($edit&&$auth->canWrite()): ?><form method="post" class="danger-zone" data-confirm="Excluir este produto?"><?= csrf_field() ?><input type="hidden" name="action" value="delete_product"><input type="hidden" name="id" value="<?= (int)$edit['id'] ?>"><button>Excluir produto</button></form><?php endif; ?></section></div><?php endif; ?>

