<?php
use App\Services\FinanceService;
[$from,$to,$periodLabel]=period_dates();$rate=$rates->current();$finance=new FinanceService($db);$metrics=$finance->dashboard($from,$to,$rate['bid']);$series=$finance->monthlySeries(12);
$byCountry=$db->fetchAll("SELECT c.country,COUNT(DISTINCT p.client_id) clients,COALESCE(SUM(p.amount_brl),0) revenue FROM payments p JOIN clients c ON c.id=p.client_id WHERE p.status='paid' AND p.payment_date BETWEEN ? AND ? GROUP BY c.country ORDER BY revenue DESC",[$from,$to]);
$byCurrency=$db->fetchAll("SELECT currency,COUNT(*) payments,COALESCE(SUM(amount),0) original,COALESCE(SUM(amount_brl),0) brl FROM payments WHERE status='paid' AND payment_date BETWEEN ? AND ? GROUP BY currency ORDER BY brl DESC",[$from,$to]);
$byProduct=$db->fetchAll("SELECT COALESCE(pr.name,'Pagamentos avulsos') product,COUNT(pa.id) payments,COALESCE(SUM(pa.net_brl),0) revenue FROM payments pa LEFT JOIN subscriptions s ON s.id=pa.subscription_id LEFT JOIN products pr ON pr.id=s.product_id WHERE pa.status='paid' AND pa.payment_date BETWEEN ? AND ? GROUP BY COALESCE(pr.name,'Pagamentos avulsos') ORDER BY revenue DESC LIMIT 8",[$from,$to]);
$byCategory=$db->fetchAll("SELECT category,COALESCE(SUM(amount_brl),0) total FROM expenses WHERE status='paid' AND payment_date BETWEEN ? AND ? GROUP BY category ORDER BY total DESC LIMIT 8",[$from,$to]);
$maxProduct=max(array_column($byProduct,'revenue')?:[1]);$maxCategory=max(array_column($byCategory,'total')?:[1]);
?>
<section class="toolbar dashboard-toolbar"><form method="get" class="period-filter"><input type="hidden" name="page" value="reports"><label>Período<select name="period"><option value="month">Este mês</option><option value="quarter" <?= ($_GET['period']??'')==='quarter'?'selected':'' ?>>Últimos 3 meses</option><option value="year" <?= ($_GET['period']??'')==='year'?'selected':'' ?>>Este ano</option><option value="custom" <?= ($_GET['period']??'')==='custom'?'selected':'' ?>>Personalizado</option></select></label><label>De<input name="from" type="date" value="<?= h($from) ?>"></label><label>Até<input name="to" type="date" value="<?= h($to) ?>"></label><button class="button secondary">Gerar relatório</button></form><div class="export-group"><a class="button ghost" href="?page=export&type=payments">⇩ Pagamentos CSV</a><a class="button ghost" href="?page=export&type=expenses">⇩ Gastos CSV</a></div></section>
<section class="report-summary card"><div><span>FATURAMENTO</span><strong><?= money($metrics['gross']) ?></strong><small><?= h($periodLabel) ?></small></div><i>−</i><div><span>TAXAS + CUSTOS</span><strong><?= money($metrics['fees']+$metrics['expenses']+$metrics['investments']) ?></strong><small>Despesas e investimentos</small></div><i>=</i><div class="highlight"><span>RESULTADO</span><strong class="<?= $metrics['profit']<0?'negative':'positive' ?>"><?= money($metrics['profit']) ?></strong><small><?= number_format($metrics['margin'],1,',','.') ?>% de margem</small></div></section>
<section class="dashboard-grid reports-grid"><article class="card chart-card"><div class="card-header"><div><p class="eyebrow">EVOLUÇÃO EM 12 MESES</p><h2>Entradas e saídas</h2></div><div class="chart-legend"><span><i class="revenue"></i> Entradas</span><span><i class="cost"></i> Saídas</span></div></div><div class="bar-chart" data-chart='<?= h(json_encode($series,JSON_UNESCAPED_UNICODE)) ?>'></div></article><article class="card"><div class="card-header"><div><p class="eyebrow">POR MOEDA</p><h2>Origem do faturamento</h2></div></div><div class="currency-report"><?php if(!$byCurrency): ?><div class="empty-mini">Sem dados no período.</div><?php endif; ?><?php foreach($byCurrency as $row): ?><div><span class="currency-mark <?= strtolower($row['currency']) ?>"><?= h($row['currency']) ?></span><span><b><?= money($row['original'],$row['currency']) ?></b><small><?= (int)$row['payments'] ?> pagamentos</small></span><strong><?= money($row['brl']) ?></strong></div><?php endforeach; ?></div><div class="rate-foot">Cotação atual de referência: US$ 1 = <?= money($rate['bid']) ?></div></article></section>
<section class="dashboard-grid reports-grid"><article class="card"><div class="card-header"><div><p class="eyebrow">RECEITA POR PRODUTO</p><h2>O que mais fatura</h2></div></div><div class="rank-bars"><?php if(!$byProduct): ?><div class="empty-mini">Sem dados no período.</div><?php endif; ?><?php foreach($byProduct as $row): ?><div><span><b><?= h($row['product']) ?></b><small><?= (int)$row['payments'] ?> pagamentos</small></span><strong><?= money($row['revenue']) ?></strong><i style="--width:<?= $maxProduct>0?round($row['revenue']/$maxProduct*100):0 ?>%"></i></div><?php endforeach; ?></div></article><article class="card"><div class="card-header"><div><p class="eyebrow">SAÍDAS POR CATEGORIA</p><h2>Para onde vai o dinheiro</h2></div></div><div class="rank-bars costs"><?php if(!$byCategory): ?><div class="empty-mini">Sem dados no período.</div><?php endif; ?><?php foreach($byCategory as $row): ?><div><span><b><?= h($row['category']) ?></b></span><strong><?= money($row['total']) ?></strong><i style="--width:<?= $maxCategory>0?round($row['total']/$maxCategory*100):0 ?>%"></i></div><?php endforeach; ?></div></article></section>
<section class="card country-report"><div class="card-header"><div><p class="eyebrow">MERCADOS</p><h2>Brasil x Estados Unidos</h2></div></div><div><?php if(!$byCountry): ?><div class="empty-mini">Sem pagamentos no período.</div><?php endif; ?><?php foreach($byCountry as $row): ?><article><span class="country-flag"><?= $row['country']==='BR'?'🇧🇷':'🇺🇸' ?></span><span><b><?= $row['country']==='BR'?'Brasil':'Estados Unidos' ?></b><small><?= (int)$row['clients'] ?> clientes pagantes</small></span><strong><?= money($row['revenue']) ?></strong></article><?php endforeach; ?></div></section>
